server:
  servlet:
    context-path: /restdoc
  port: 8432

spring:
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
    cache: false


  redis:
    database: 10
    host: ${REDIS-HOST}
    lettuce:
      pool:
        max-active: 200   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 0     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: 'overman@@2020'
    port: 6377
  data:
    mongodb:
      authentication-database: non_standard
      username: front_biz
      password: qmbxfrontbizStorage
      database: non_standard
      host: ${MONGO-HOST}
      port: 27017

restdoc:
  schedule:
    port: 4321


